<a href="https://colab.research.google.com/github/Reji20/Datascience--lab/blob/main/Pruning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score,confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/Heart (1).csv')
df.head()

   Unnamed: 0  Age  Sex     ChestPain  ...  Slope   Ca        Thal  AHD
0           1   63    1       typical  ...      3  0.0       fixed   No
1           2   67    1  asymptomatic  ...      2  3.0      normal  Yes
2           3   67    1  asymptomatic  ...      2  2.0  reversable  Yes
3           4   37    1    nonanginal  ...      3  0.0      normal   No
4           5   41    0    nontypical  ...      1  0.0      normal   No

[5 rows x 15 columns]

In [ ]:
X = df.drop(columns=['AHD'])
y = df['AHD']